### PR TITLE
[FIX JENKINS-48791] Add NPE check for tool name

### PR DESCRIPTION
**Pull request by skundrik**

### CODE REVIEW

**Comment by skundrik** [comment]
@oleg-nenashev any chance you can have a quick look?

**Comment by oleg-nenashev** [comment]
In my queue. Note that I am not the plugin's maintainer,  so my review may not be enough

**Comment by skundrik** [comment]
Thanks anyway, it's just adding NPE check when plugins providing installations on on Global tool config return null instead of empty string, like nuget one does.

**Comment by skundrik** [comment]
@oleg-nenashev would you be able to review this tiny change? It' sat here for ages. Would be good to get it over the line.

**Review by oleg-nenashev — APPROVED** [review]
Right, this change is fairly straightforward. +1 for it

**Comment by skundrik** [comment]
@jglick ,can you merge this tiny change? @oleg-nenashev has already reviewed it as well.

**Comment by jglick** [comment]
I am not a maintainer.

**Comment by jglick** [comment]
Check the plugin adoption process if you are interested.

**Comment by skundrik** [comment]
The plugin page https://plugins.jenkins.io/toolenv/ says that you are that's why I pinged you. Are you saying you'd like to give it up for adoption?

**Comment by timja** [comment]
@jglick you’re the only one listed in the Pom, and seem to have done most of the commits, 

Did you want to mark it for adoption / approve skundrik’s adoption?

**Comment by jglick** [comment]
Evidently I cut a release _seven years ago_, I no longer recall why; and I do not have write permission now. If someone wants to adopt it, go ahead.

**Comment by jglick** [comment]
Apparently I actually wrote this plugin, a decade ago. Very little memory of that. :shrug: Anyway `ToolInstallation` is basically obsolete at this point in human history—use containers, e.g. from the `kubernetes` plugin.

**Pull request merged**
